import express from 'express';
import { createCategory, deleteCategory, getCategories, updateCategory } from '../controllers/categoryController.js';
import { authorize, protect } from '../middlewares/authMiddleware.js';
import validate from '../middlewares/validate.js';
import { categorySchema } from '../validations/categoryValidation.js';
const router = express.Router();
router.get('/', getCategories);
router.post('/', protect, authorize('admin'), validate(categorySchema), createCategory);
router.patch('/:id', protect, authorize('admin'), validate(categorySchema), updateCategory);
router.delete('/:id', protect, authorize('admin'), deleteCategory);
export default router;
